neizlesem_proje/neizlesem_proje/Controllers/FavoriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using neizlesem_proje.Models;
using PagedList;

namespace neizlesem_proje.Controllers
{

    public class FavoriController : Controller
    {
        private neizlesem db = new neizlesem();
        // GET: Favori
        public ActionResult Index(int? sayfa,int? uye_no)
        {
            var sayfa_no = sayfa ?? 1;
            uye_no = ((Uye)Session["uyem"]).uye_no;
            var favoriler = db.favoriler.Where(x=>x.uye_no==uye_no).ToList().ToPagedList(sayfa_no, 15);
            return View(favoriler);
        }
        public ActionResult favori_ekle(int id, int? uye_no)
        {
            try
            {
                if (Session["uyem"] == null)
                {
                    ViewBag.uyari = "Favorilere ekleyebilmek için giriş yapmalısınız.";
                    return RedirectToAction("Index", "Film");
                }
                else
                {
                    Favori favori = new Favori() { film_no = id, uye_no = ((Uye)Session["uyem"]).uye_no };
                    var favoriler = db.favoriler.Add(favori);
                    db.SaveChanges();
                }
            }
            catch (Exception)
            {
                ViewBag.uyari = "Bu film zaten favorilerinizde.";
            }
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            Favori favori = await db.favoriler.FindAsync(id);
            if (favori == null)
            {
                return HttpNotFound();
            }
            db.favoriler.Remove(favori);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

neizlesem_proje/neizlesem_proje/Controllers/FilmController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using neizlesem_proje.Models;
using PagedList;
using System.Threading.Tasks;
using System.Net;
using System.IO;

namespace neizlesem_proje.Controllers
{
    public class FilmController : Controller
    {
        private neizlesem db = new neizlesem();
        // GET: Film
        public ActionResult Index(int? sayfa, int? id)
        {
            var sayfa_no = sayfa ?? 1;
            IEnumerable<Film> filmler = null;
            if (id == null)
            {

                filmler = db.filmler.ToList().ToPagedList(sayfa_no,15);
            }
            else
            filmler = db.filmler.ToList().Where(x => x.tur_no == id).ToPagedList(sayfa_no,15);
            ViewBag.filmler = filmler;
            return View(filmler);
        }

        public ActionResult Index2(int? sayfa, int? id)
        {
            var sayfa_no = sayfa ?? 1;
            IEnumerable<Film> filmler = null;
            if (id == null)
            {

                filmler = db.filmler.ToList().ToPagedList(sayfa_no, 15);
            }
            else
                filmler = db.filmler.ToList().Where(x => x.tur_no == id).ToPagedList(sayfa_no, 15);
            ViewBag.filmler = filmler;
            return View(filmler);
        }

        public ActionResult film_goster(int id)
        {
            var film = db.filmler.ToList().Where(x=>x.film_no==id);
            return View(film);
        }
        public ActionResult Create()
        {
            ViewBag.tur_no = new SelectList(db.turler, "tur_no", "tur_adi");
            ViewBag.yonetmen_no = new SelectList(db.yonetmenler, "yonetmen_no", "yonetmen_adsoyad");
            return View();
        }

        // POST: Filmsv23/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "film_no,film_adi,film_ozeti,tur_no,film_afis,film_cikis_tarih,puan,yonetmen_no,yildizlar")] Film film,HttpPostedFileBase file)
        {
            string dosya_adi = "stokfoto.png";
            if (file != null)
            {
                if (file.ContentLength > 0)
                {
                    string uzanti = Path.GetExtension(file.FileName);
                    if (uzanti.Equals(".jpg") || uzanti.Equals(".png") || uzanti.Equals(".jpeg"))
                    {
                        dosya_adi = Path.GetFileName(file.FileName);
                        string yol = Path.Combine(Server.MapPath("~/film_afisleri"), dosya_adi);
                        file.SaveAs(yol);
                        ViewBag.msg = "Film kaydedildi.";
                    }
                    else
                    {
                        ViewBag.msg = "Resim formatı png,jpg veya jpeg olmalı.";
                    }
                }
                else
                {
                    ViewBag.msg = "Film stok resim ile kaydedildi.";
                }
            }
            film.film_afis = dosya_adi;
            if (ModelState.IsValid)
            {
                db.filmler.Add(film);
                await db.SaveChangesAsync();
                return RedirectToAction("Index2");
            }

            ViewBag.tur_no = new SelectList(db.turler, "tur_no", "tur_adi", film.tur_no);
            ViewBag.yonetmen_no = new SelectList(db.yonetmenler, "yonetmen_no", "yonetmen_adsoyad", film.yonetmen_no);
            return View(film);
        }

        // GET: Filmsv23/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Film film = await db.filmler.FindAsync(id);
            if (film == null)
            {
                return HttpNotFound();
            }
            ViewBag.tur_no = new SelectList(db.turler, "tur_no", "tur_adi", film.tur_no);
            ViewBag.yonetmen_no = new SelectList(db.yonetmenler, "yonetmen_no", "yonetmen_adsoyad", film.yonetmen_no);
            return View(film);
        }

        // POST: Filmsv23/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "film_no,film_adi,film_ozeti,tur_no,film_afis,film_cikis_tarih,puan,yonetmen_no,yildizlar")] Film film)
        {
            if (ModelState.IsValid)
            {
                db.Entry(film).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index2");
            }
            ViewBag.tur_no = new SelectList(db.turler, "tur_no", "tur_adi", film.tur_no);
            ViewBag.yonetmen_no = new SelectList(db.yonetmenler, "yonetmen_no", "yonetmen_adsoyad", film.yonetmen_no);
            return View(film);
        }

        // GET: Filmsv23/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Film film = await db.filmler.FindAsync(id);
            if (film != null)
            {
                db.filmler.Remove(film);
                await db.SaveChangesAsync();
                return RedirectToAction("Index2");
            }
            return View(film);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [HttpGet]
        public ActionResult film_oner()
        {
            alanlari_doldur();
            return View();
        }
        [HttpPost]

        /* onerilen filmler action u IEnumerable<Film> onerilen_film, int? sayfa */
        public ActionResult film_oner(double? puan, int? tur_no, int? film_cikis_tarih)
        {
            alanlari_doldur();
            var onerilen_films = db.filmler.Where(x => x.puan == puan && x.tur_no == tur_no && x.film_cikis_tarih.Year == film_cikis_tarih);
            return RedirectToAction("onerilen_filmler", new { puani = puan, turno=tur_no,cikistarih=film_cikis_tarih});

        }

        // buraya null geliyor onerilen_films coz
        public ActionResult onerilen_filmler(double? puani,int? turno,int? cikistarih,int? sayfa)
        {
            var sayfa_no = sayfa ?? 1;
            IEnumerable<Film> film = null;
            if (puani == 9)
            {
                if (cikistarih != 2015 && cikistarih != 2010 && cikistarih != 2000)
                {
                    film = db.filmler.ToList().Where(x => x.puan <= 9 && x.puan >= 8 && x.tur_no == turno && x.film_cikis_tarih.Year == cikistarih).ToPagedList(sayfa_no, 15);
                }
                else if (cikistarih == 2000)
                {
                    film = db.filmler.ToList().Where(x => x.puan <= 9 && x.puan >= 8 && x.tur_no == turno && x.film_cikis_tarih.Year <= cikistarih).ToPagedList(sayfa_no, 15);
                }
                else if (cikistarih == 2015)
                {
                    film = db.filmler.ToList().Where(x => x.puan <= 9 && x.puan >= 8 && x.tur_no == turno && x.film_cikis_tarih.Year <= 2015 && x.film_cikis_tarih.Year >= 2010).ToPagedList(sayfa_no, 15);
                }
                else
                {
                    film = db.filmler.ToList().Where(x => x.puan <= 9 && x.puan >= 8 && x.tur_no == turno && x.film_cikis_tarih.Year <= 2010 && x.film_cikis_tarih.Year >= 2000).ToPagedList(sayfa_no, 15);

                }
            
            }
            else if (puani == 8)
            {
                if (cikistarih != 2015 && cikistarih != 2010 && cikistarih != 2000)
                {
                    film = db.filmler.ToList().Where(x => x.puan <= 8 && x.puan >= 7 && x.tur_no == turno && x.film_cikis_tarih.Year == cikistarih).ToPagedList(sayfa_no, 15);
                }
                else if (cikistarih == 2000)
                {
                    film = db.filmler.ToList().Where(x => x.puan <= 8 && x.puan >= 7 && x.tur_no == turno && x.film_cikis_tarih.Year <= cikistarih).ToPagedList(sayfa_no, 15);
                }
                else if (cikistarih == 2015)
                {
                    film = db.filmler.ToList().Where(x => x.puan <= 8 && x.puan >= 7 && x.tur_no == turno && x.film_cikis_tarih.Year <= 2015 && x.film_cikis_tarih.Year >= 2010).ToPagedList(sayfa_no, 15);
                }
                else
                {
                    film = db.filmler.ToList().Where(x => x.puan <= 8 && x.puan >= 7 && x.tur_no == turno && x.film_cikis_tarih.Year <= 2010 && x.film_cikis_tarih.Year >= 2000).ToPagedList(sayfa_no, 15);

                }

            }
            else if (puani == 7)
            {
                if (cikistarih != 2015 && cikistarih != 2010 && cikistarih != 2000)
                {
                    film = db.filmler.ToList().Where(x => x.puan <= 7 && x.puan >= 6 && x.tur_no == turno && x.film_cikis_tarih.Year == cikistarih).ToPagedList(sayfa_no, 15);
                }
                else if (cikistarih == 2000)
                {
                    film = db.filmler.ToList().Where(x => x.puan <= 7 && x.puan >= 6 && x.tur_no == turno && x.film_cikis_tarih.Year <= cikistarih).ToPagedList(sayfa_no, 15);
                }
                else if (cikistarih == 2015)
                {

neizlesem_proje/neizlesem_proje/Controllers/UyesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using neizlesem_proje.Models;

namespace neizlesem_proje.Controllers
{
    public class UyesController : Controller
    {
        private neizlesem db = new neizlesem();

        // GET: Uyes
        public async Task<ActionResult> Index()
        {
            return View(await db.uyeler.ToListAsync());
        }

        // GET: Uyes/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Uye uye = await db.uyeler.FindAsync(id);
            if (uye == null)
            {
                return HttpNotFound();
            }
            return View(uye);
        }
        // GET: Uyes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Uyes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        
        public async Task<ActionResult> Create([Bind(Include = "uye_no,ad_soyad,uye_mail,kul_adi,sifre")] Uye uye)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    db.uyeler.Add(uye);
                    await db.SaveChangesAsync();
                    ViewBag.kayit_durum = " Kayıt başarılı. Giriş yapabilirsiniz.";
                }  
                catch (Exception hata)
                {
                    int yeri = hata.InnerException.ToString().IndexOf("uk_uyeler_uye_mail"); //-1 döndürürse kullanıcı adı hatasıdır
                    if (yeri != -1)
                    {
                        ViewBag.kayit_durum = "Bu e-mail sistemizde kayıtlıdır. Başka bir e-mail deneyiniz.";
                    }
                    else
                    {
                        ViewBag.kayit_durum = "Bu kullanıcı adı kullanımda. Başka bir kullanıcı adı deneyiniz.";
                        List<string> kuladi_onerilerim = kullanici_adi_oner(uye.kul_adi);
                        ViewBag.kuladi_onerilerim = kuladi_onerilerim;
                    }
                }
            }
            return View(uye);
        }

        // GET: Uyes/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null || Session["uyem"] == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Uye uye = await db.uyeler.FindAsync(id);
            if (uye == null)
            {
                return HttpNotFound();
            }
            return View(uye);
        }

        // POST: Uyes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "uye_no,ad_soyad,uye_mail,kul_adi,sifre")] Uye uye)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    db.Entry(uye).State = EntityState.Modified;
                    await db.SaveChangesAsync();
                    ViewBag.durumu = "Bilgileriniz güncellendi.";
                    Session.RemoveAll();
                    Session.Abandon();
                    Task.WaitAll(Task.Delay(1000));
                    return RedirectToAction("uye_giris", "Home");
                }
                catch (Exception hata)
                {
                    int yeri = hata.InnerException.ToString().IndexOf("uk_uyeler_uye_mail");
                    if (yeri != -1)
                    {
                        ViewBag.durumu = "Bu e-mail kullanımda. Başka bir email deneyiniz.";
                    }
                    else
                    {
                        ViewBag.durumu = "Bu kullanıcı adı kullanımda. Başka bir kullanıcı adı deneyiniz.";
                    }
                }
            }
            return View(uye);
        }

        // GET: Uyes/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Uye uye = await db.uyeler.FindAsync(id);
            if (uye == null)
            {
                return HttpNotFound();
            }
            db.uyeler.Remove(uye);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        List<string> kuladi_oneri_listemiz = new List<string>();
        byte sayac = 0;
        List<string> kullanici_adi_oner(string kuladi)
        {
            System.Threading.Thread.Sleep(500); //random sistem saatine göre çalışır sistemi sleep ile yavaşlatmazsam random aynı şeyleri üretir !!
            string[] harfler = { "a", "b", "c", "d", "p", "r", "f" };
            string oneri_kuladi = kuladi + DateTime.Now.Year + harfler[new Random().Next(0, 4)];
            int mevcutmu = db.uyeler.Where(x => x.kul_adi == oneri_kuladi).Count();
            if (mevcutmu == 0)//dbde yok demektir
            {
                kuladi_oneri_listemiz.Add(oneri_kuladi);
                sayac++;
            }
            if (sayac != 3) kullanici_adi_oner(kuladi);
            return kuladi_oneri_listemiz;
        }
    }
}

neizlesem_proje/neizlesem_proje/Views/Shared/_Layout.cshtml
@using neizlesem_proje.Models
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Ne İzlesem?</title>
    <link rel="stylesheet" href="~/Content/style.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">

</head>
<body>
<div class="navbar">
    <div class="navbar-wrapper">
        <div class="logo-wrapper">
            <h1 class="logo"><i>Ne izlesem? </i></h1>
        </div>
        <div class="menu-container">
            <ul class="menu-list">
                <li class="menu-list-item active">
                    <a href="#">
                        Ana sayfa
                    </a>
                </li>
                <li class="menu-list-item">
                        Kategoriler
                        <ul>
                            <li>
                                <a href="#">  Bişeyler </a>
                            </li>
                            <li>
                                <a href="#">  2BİŞEYLER </a>
                            </li>
                        </ul>
                </li>
                <li class="menu-list-item">
                    <a href="#">
                        Haberler
                    </a>
                </li>
                <li class="menu-list-item">
                    <a href="#">
                        Favoriler
                    </a>
                </li>
                <li class="menu-list-item">
                    <a href="#">
                        Daha sonra izlenecekler
                    </a>
                </li>
            </ul>
        </div>
        <div class="profil-container">
            <div class="profile-text-container">
                <span class="profile-text">Hesabım</span>
                <i class="bi bi-caret-down-fill"></i>
            </div>
            @*  <div class="toggle">
            <i class="bi bi-moon-fill toggle-icon"></i>
            <i class="bi bi-brightness-high-fill toggle-icon"></i>
            <div class="toggle-ball">

            </div>
        </div> *@
        </div>
    </div>
</div>
<div class="content">
    <div class="content-wrapper">
        @RenderBody()
        icerik
    </div>
</div>
    <footer>
        Ne izlesem? since 2023
    </footer>
</body>
</html>

neizlesem_proje/neizlesem_proje/Views/Shared/_Layoutv2.cshtml
@using neizlesem_proje.Models
<!DOCTYPE html>
@{
    string adsoyad = "Ziyaretçi";
    if (Session["uyem"] != null)
    {
        adsoyad = ((Uye)Session["uyem"]).ad_soyad;
    }
}
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Ne İzlesem?</title>
    <link rel="shortcut icon" href="~/film_afisleri/questmark.png" />
    <link rel="stylesheet" href="~/Content/layoutum.css" />
    <link rel="stylesheet" href="~/Content/kayitgiris.css" />
    <link rel="stylesheet" href="~/Content/PagedList.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <nav>
        <label class="logo" for=""> <img src="~/film_afisleri/logodeneme6.png" /> </label>
        <ul>
            @if (Session["uyem"] == null)
            {
                <li><a class="active" href="@Url.Action("Index","Film")"><i class="fa-regular fa-solid fa-house"></i> Ana sayfa</a></li>
                <li><a href="@Url.Action("film_oner","Film")"><i class="fa-regular fa-question"></i> Film öner</a></li>
                <li class="kategori-li">
                    <a href="#"><i class="fa-solid fa-bars"></i> Kategoriler </a>
                    <div id="kategoriler-content">
                        @{ Html.RenderAction("tur_doldur", "Home");}
                        @* <ul>
                                <li style="display:block;"> <a href="#"> Aksiyon </a> </li>
                                <li style="display:block;"> <a href="#"> Macera </a> </li>
                                <li style="display:block;"> <a href="#"> Korku </a> </li>
                            </ul> *@
                    </div>
                </li>
                <li><a href="@Url.Action("sinema","Home")"><i class="fa-solid fa-film"></i> Sinema</a></li>
                <li><a href="@Url.Action("Create","Uyes")"><i class="fa-solid fa-right-to-bracket"></i> Üye ol </a></li>
                <li><a href="@Url.Action("uye_giris","Home")"><i class="fa-regular fa-user"></i> Giriş yap</a></li>
            }
            else if (Session["admin"] == null)
            {
                <li><a class="active" href="@Url.Action("Index","Film")"><i class="fa-regular fa-solid fa-house"></i> Ana sayfa</a></li>
                <li><a href="@Url.Action("film_oner","Film")"><i class="fa-regular fa-question"></i> Film öner</a></li>
                <li class="kategori-li">
                    <a href="#"><i class="fa-solid fa-bars"></i> Kategoriler </a>
                    <div id="kategoriler-content">
                        @{ Html.RenderAction("tur_doldur", "Home");}
                        @* <ul>
                                <li style="display:block;"> <a href="#"> Aksiyon </a> </li>
                                <li style="display:block;"> <a href="#"> Macera </a> </li>
                                <li style="display:block;"> <a href="#"> Korku </a> </li>
                            </ul> *@
                    </div>
                </li>
                <li><a href="@Url.Action("sinema","Home")"><i class="fa-solid fa-film"></i> Sinema</a></li>
                <li><a href="@Url.Action("Edit","Uyes",new {id = ((Uye)Session["uyem"]).uye_no })"><i class="fa-solid fa-user-pen"></i> Üye bilgileri güncelle </a></li>
                <li><a href="@Url.Action("Index","Favori")"><i class="fa-solid fa-heart"></i> Favoriler </a></li>
                <li><a href="@Url.Action("guv_cik","Home")"><i class="fa-solid fa-arrow-right-from-bracket"></i> Çıkış yap</a></li>
            }
            else
            {
                <li><a class="active" href="@Url.Action("Index2","Film")"><i class="fa-regular fa-solid fa-house"></i>Tüm filmleri gör</a></li>
                <li><a href="@Url.Action("Create","Yonetmen")"><i class="fa-solid fa-floppy-disk"></i> Yönetmen kaydet </a></li>
                <li><a href="@Url.Action("Index","Yonetmen")"><i class="fa-solid fa-users"></i> Yönetmenleri gör </a></li>
                <li><a href="@Url.Action("Create","Film")"><i class="fa-solid fa-floppy-disk"></i> Film kaydet </a></li>
                <li><a href="@Url.Action("Create","Uyes")"><i class="fa-solid fa-users"></i> Üye kayıt</a></li>
                <li><a href="@Url.Action("Index","Uyes")"><i class="fa-solid fa-users"></i> Üyeleri gör </a></li>
                <li><a href="@Url.Action("guv_cik","Home")"><i class="fa-solid fa-arrow-right-from-bracket"></i> Çıkış yap</a></li>
            }


        </ul>

    </nav>
    <div class="content">
        <label class="hosgeldin" style="color:white; text-align:center"> Hoş geldin @adsoyad </label>
        <br />
        @RenderBody()
    </div>
    <br />
    <footer>
        <hr style="width:1000px; margin: auto;" /> <i class="fa-brands fa-facebook"></i> <i class="fa-brands fa-twitter"></i> <i class="fa-brands fa-instagram"></i> /neizlesem <label class="biseyler"> © 2023 Ne izlesem. </label>
    </footer>
    <script>
let slideIndex = 1;
showSlides(slideIndex);

function plusSlides(n) {
  showSlides(slideIndex += n);
}

function currentSlide(n) {
  showSlides(slideIndex = n);
}

function showSlides(n) {
  let i;
  let slides = document.getElementsByClassName("mySlides");
  let dots = document.getElementsByClassName("dot");
  if (n > slides.length) {slideIndex = 1}
  if (n < 1) {slideIndex = slides.length}
  for (i = 0; i < slides.length; i++) {
    slides[i].style.display = "none";
  }
  for (i = 0; i < dots.length; i++) {
    dots[i].className = dots[i].className.replace(" active", "");
  }
  slides[slideIndex-1].style.display = "block";
  dots[slideIndex-1].className += " active";
}
    </script>
</body>
</html>